### ISSUE TITLE
Chum metadata

### ISSUE THREAD

**Issue by rinigus** [monich/harbour-wordle#14]
We have added metadata support in SailfishOS:Chum GUI. This allows to categorize applications, show their icons, screenshots. Much of data is pulled from GitHub/GitLab repos, such as developer name, releases and issues. 

As we don't have central server for metadata, we use SPEC to provide it. Namely, we ask developers to add it under description section in SPEC. In context of Wordle, it would change description field in SPEC to 

```
%description
Guess the WORDLE in 6 tries

%if "%{?vendor}" == "chum"
Categories:
 - Game
Icon: https://raw.githubusercontent.com/monich/harbour-wordle/master/icons/harbour-wordle.svg
Screenshots:
 - https://openrepos.net/sites/default/files/packages/7548/screenshot-wordle-3a.png
 - https://openrepos.net/sites/default/files/packages/7548/screenshot-wordle-1a.png
 - https://openrepos.net/sites/default/files/packages/8407/screenshot-wordle-2.png
%endif

%prep
%setup -q -n %{name}-%{version}
```
(... and SPEC continues)

Few of us have added screenshots into Github repositories. For example, for Pure Maps I have https://github.com/rinigus/pure-maps/tree/master/screenshots and I use screenshot urls (in "raw" format) from there. Same could be applied here as well. 

Used metadata API is described at https://github.com/sailfishos-chum/main/blob/main/Metadata.md

Note that the packages which have `vendor` set to something else then either should drop `%if` section from SPEC or change accordingly. Personally, I don't use that %if and have it always included.

**Comment by monich** [comment]
ok, I'll add the metadata in the next release. I've already added it to harbour-counter, does [that](https://github.com/monich/harbour-counter/commit/199fd5c) look ok?

**Comment by rinigus** [comment]
Thank you, looking forward. Feedback regarding Counter:

```
PackageName: Counter
Type: desktop-application
DeveloperName: Slava Monich
```
In the case of Counter, Chum GUI would automatically strip `harbour-` from package name and set its name to "Counter" (capitalized that way), Type to desktop-application. Your name is also pulled from GitHub as "Slava Monich (monich)" as you have repository URL specified in SPEC in 2 places: `URL:` field of SPEC and in Chum metadata under Custom/Repo. So, as such, you could have skipped those 3 lines.

```
Custom:
  Repo: https://github.com/monich/harbour-counter
```
As URL points to GitHub already, you don't need that either.

```
Icon: https://github.com/monich/harbour-counter/blob/master/icons/harbour-counter.svg
```
This doesn't work as we need URI which is set to be shown via QML Image. So, in this case, it should be 
```
Icon: https://raw.githubusercontent.com/monich/harbour-counter/master/icons/harbour-counter.svg
```

Screenshots load as needed. Bugtracker is also automatically set as URL is from GitHub. Homepage would not be set to OpenRepos page. So, that needs to be set in metadata as you did. 

In addition to fix in Icon, would be great to have the application categorized. You can set many categories, if you wish. We use categories from https://specifications.freedesktop.org/menu-spec/latest/apa.html and https://specifications.freedesktop.org/menu-spec/latest/apas02.html . I guess, Counter is "Utility".

So, in summary, you could reduce your Counter case to 

```
%if "%{?vendor}" == "chum"
Categories:
 - Utility
Icon: https://raw.githubusercontent.com/monich/harbour-counter/master/icons/harbour-counter.svg
Screenshots:
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-001.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-002.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-003.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-004.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-005.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-006.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-007.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-008.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-009.png
- https://home.monich.net/chum/harbour-counter/screenshots/screenshot-010.png
Url:
  Homepage: https://openrepos.net/content/slava/counter
%endif
```

**Comment by monich** [comment]
> ```
> Icon: https://github.com/monich/harbour-counter/blob/master/icons/harbour-counter.svg
> ```
> 
> 
>     
>   
> 
> This doesn't work as we need URI which is set to be shown via QML Image. So, in this case, it should be

Yes, indeed that URL returns an html, I haven't checked that. I'll fix it next time I touch that spec.

**Comment by monich** [comment]
And I did this for WODLE too. How does 1.0.5 look?

**Comment by rinigus** [comment]
Looks exactly as it should - thank you!

Closing as the issue is resolved. Please feel free to ping me via it - would be happy to help
