### ISSUE TITLE
Dutch files

### ISSUE THREAD

**Issue by cow-n-berg** [monich/harbour-wordle#4]
Hi Slava,

I compiled the lists for Nederlands (Dutch) and it seems to work on my X10ii.

As you may see, I tried a different place for the Backspace and the Next button. I like it better. It would be even better when those buttons would be smaller. Why not the same width, or max 1.5 times the width?

A word on the content for the Dutch readers: 
Herkomst: OpenTaal-210G-basis-gekeurd. Hoofdletters niet opgenomen, evenals varianten van letters zoals èêéë. Geen werkwoordvervoegingingen. Verder amper inhoudelijke redactie.

Great game, thanks!

Kind regards, Rob

[dutch.zip](https://github.com/monich/harbour-wordle/files/7965591/dutch.zip)

**Comment by monich** [comment]
Included in release [1.0.2](https://github.com/monich/harbour-wordle/releases/tag/1.0.2), thanks!
